Parser is done.
ravndaa/gameoflife-csharp pull request #9
Opened 2020-09-30 18:44 UTC by ravndaa

Parser is done, and should be added before starting on the actual work.

2020-09-30 19:58 UTC, netbrain requested changes

2020-09-30 19:58 UTC, netbrain commented on gameoflife.lib/GOLInput.cs
> +        public int[] BoardSize {get;set;} // x and y
Should be a width and height IMO. Not a array.

2020-09-30 19:58 UTC, netbrain commented on gameoflife.lib/GOLInput.cs
> +    }
Why keep the raw value? Just use a int for the generation

2020-09-30 19:58 UTC, netbrain commented on gameoflife.lib/gameoflifelib.cs
> +            var result = int.Parse(Regex.Match(s, regexPattern).Groups[1].ToString());
How would this handle incorrect syntax? Try writing a test to see how it would handle it if generation was missing or not a number.

2020-09-30 19:58 UTC, netbrain commented on gameoflife.lib/gameoflifelib.cs
> +            var generation = new Generation { Raw = s[0], Value = GetGenerationValue(s[0]) };
An int is enough?

2020-09-30 19:58 UTC, netbrain commented on gameoflife.lib/gameoflifelib.cs
> +            var regexPattern = @"((\d+)\s(\d+))";
This regex works fine, but IMO this is overkill for such a simple syntax. This line is simply two number separated by a space. I would simply Split the string on Said space and return both as integers

2020-09-30 19:58 UTC, netbrain commented on gameoflife.lib/gameoflifelib.cs
> +            int rowss = rows + 2; // hakk
Just strip the two First rows from the input before passing it to this function

2020-09-30 19:58 UTC, netbrain commented on gameoflife.test/TestGOLLibrary.cs
> +            Assert.IsType<GOLData>(actual);
This test does not have much value.

2020-09-30 19:58 UTC, netbrain commented on gameoflife.test/TestGOLLibrary.cs
> +            Assert.Equal(wants, actual.Board);
You could probably combine these (3 above) tests together.

2020-09-30 19:58 UTC, netbrain commented on gameoflife.test/TestGOLLibrary.cs
> +            Assert.Equal('*', actual.Board[1][4]);
This is useless given the test above

2020-09-30 19:58 UTC, netbrain commented on gameoflife.test/TestGOLLibrary.cs
> +
Empty test

2020-10-01 08:31 UTC, netbrain commented on gameoflife.lib/gameoflifelib.cs
> +            var result = int.Parse(Regex.Match(s, regexPattern).Groups[1].ToString());
Personally I would solve this like the following:
We already know that the first line in the input always has to start with "Generation " then comes the number and then a ":". So instead of using regex you could either, substring the string by an offset (i.e. length of "Generation ") and substring trim the end of the line which should contain a ":", the rest should then be a parsable number. If any of the conditions above fail, then throw an exception.

2020-10-01 08:31 UTC, netbrain commented on gameoflife.test/TestGOLLibrary.cs
> +            var lib = new GOL();
what kind of name is lib? I understand gol, but not lib.

2020-10-01 08:49 UTC, ravndaa commented on gameoflife.test/TestGOLLibrary.cs
> +            var lib = new GOL();
Naming is hard. 🙃 But since it tests the GOL library, lib was short, but i agree will make some changes to names.

2020-10-01 12:50 UTC, ravndaa commented
Ahh, pull requests går på branch ikke commits. 😲🙂

2020-10-01 16:57 UTC, netbrain commented
If you want a New review from me you have to re-request it under the reviewers pane

2020-10-01 17:15 UTC, ravndaa commented
@netbrain did you see the working gif i sent on slack?

2020-10-01 21:16 UTC, netbrain requested changes
Looking much better than before, but still see room for improvement.

2020-10-01 21:16 UTC, netbrain commented on gameoflife.lib/gameoflifelib.cs
> +            var firstcharparsed = int.TryParse(inputaschars[0].ToString(), out int height);
you dont check the length of the input string, should be a minimum of 3, so you would get  array out of bounds  exception if it's incorrect. also, you dont handle numbers with several digits.

2020-10-01 21:16 UTC, netbrain commented on gameoflife.test/TestGameOfLifeLibrary.cs
> +        private readonly string correctGeneration1input = "Generation 1:\n4 8\n........\n....*...\n...**...\n........\n";
these strings a butt ugly.
would write them as
```suggestion
        private readonly string correctGeneration1input = ""+
            "Generation 1:\n"+
            "4 8\n"+
            "........\n"+
            "....*...\n"+
            "...**...\n"+
            "........\n";
```

That or use a multiline string with `@""`

2020-10-01 21:16 UTC, netbrain commented on gameoflife.test/TestGameOfLifeLibrary.cs
> +        private readonly string correctGeneration1input = "Generation 1:\n4 8\n........\n....*...\n...**...\n........\n";
also these strings should probably not be global data, they belong to individual tests.

2020-10-01 21:16 UTC, netbrain commented on gameoflife.test/TestGameOfLifeLibrary.cs
> +            Assert.Throws<Exception>(() => GOL.ParseInput(wrongLenghtOfColumnsGeneration1input));
Missing test that checks for multiple digits in board size.

2020-10-05 08:05 UTC, netbrain requested changes
Er på hyttetur, men her er en 5 min review.

2020-10-05 09:55 UTC, netbrain approved these changes
Good.

2020-10-05 09:56 UTC, merged